apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    app.kubernetes.io/component: metrics-proxy
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
    app.kubernetes.io/managed-by: helm
  name: {{ include "metrics-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: metrics-proxy
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
    app.kubernetes.io/managed-by: helm
  type: ClusterIP
